replicaCount: 2
region: eu-central-1

image:
  repository: 702551696126.dkr.ecr.eu-central-1.amazonaws.com/dev-cluster-1-clerk-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  BASE_URL: "https://clerk.johnydev.com"
  publickey: "CLERK_PUBLIC_KEY"
  privatekey: "CLERK_PRIVATE_KEY"
  clerkapiurl: "CLERK_API_URL"
  secretmanager: "clerk-app-secrets"
  externalsecretname: "external-secrets-sa"