apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: BASE_URL
              value: {{ .Values.env.BASE_URL }}
            - name: CLERK_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-app-keys
                  key: {{ .Values.env.publickey }}
            - name: CLERK_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: clerk-app-keys
                  key: {{ .Values.env.privatekey }}
            - name: CLERK_API_URL
              valueFrom:
                secretKeyRef:
                  name: clerk-app-keys
                  key: {{ .Values.env.clerkapiurl }}
          ports:
            - containerPort: {{ .Values.service.targetport }}
          livenessProbe: 
            httpGet:
              path: {{ .Values.env.feedspath }}
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe: 
            httpGet:
              path: {{ .Values.env.feedspath }}
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 5
            periodSeconds: 10                  