apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: clerk-k8s-secrets
    creationPolicy: Owner
  data:
    - secretKey: CLERK_PUBLIC_KEY
      remoteRef:
        key: clerk-app-keys
        property: {{ .Values.env.publickey }}
    - secretKey: CLERK_PRIVATE_KEY
      remoteRef:
        key: clerk-app-keys
        property: {{ .Values.env.privatekey }}
    - secretKey: CLERK_API_URL
      remoteRef:
        key: clerk-app-keys
        property: {{ .Values.env.clerkapiurl }}      